% This is an autogenerated sample test for file rockPaperScissors
classdef testrockPaperScissors < matlab.unittest.TestCase
    methods (Test)
        function test_rockPaperScissors(testCase)
            % Specify the input(s) of rockPaperScissors
            p1Move = "rock";
            p2Move = "scissors";

            % Exercise the function rockPaperScissors
            actualOutput_results = rockPaperScissors(p1Move,p2Move);

            % Specify the expected output(s) of rockPaperScissors
            expectedOutput_results =  "Player 1 wins";

            testCase.verifyEqual(actualOutput_results, expectedOutput_results);
        end
    end
end